name: PR Check

on: pull_request

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    container:
      image: gcc:latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install -y clang-format

      - name: Find changed tasks
        id: changed
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..HEAD \
                   | grep -E 'members/[^/]+/task[^/]+/' \
                   | cut -d/ -f1-3 \
                   | sort -u | tr '\n' ' ')
          echo "changed_tasks=${CHANGED}" >> $GITHUB_OUTPUT

      - name: Build and test changed tasks
        if: steps.changed.outputs.changed_tasks != ''
        run: |
          for task in ${{ steps.changed.outputs.changed_tasks }}; do
            if [ -d "$task/src" ]; then
              make build-$task test-$task || exit 1
            fi
          done
