name: Task Push Check

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build_all:
    runs-on: ubuntu-latest
    container:
      image: gcc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build all tasks
        run: |
          for TASK_DIR in members/*/task*; do
            if [ -d "$TASK_DIR" ]; then
              echo "Building $TASK_DIR"
              cd "$TASK_DIR"
              mkdir -p build && cd build
              cmake .. && make
              
              if [ -f "solution" ]; then
                echo "Running solution:"
                ./solution
              fi
              
              if [ -f "tests" ]; then
                echo "Running tests:"
                ./tests
              fi
              
              cd ../../..
            else
              echo "Directory $TASK_DIR does not exist"
            fi
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-tasks-artifacts
          path: members/*/task*/build/
