name: PR Check

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Find changed tasks
        id: changed
        run: |
          CHANGED=$(git diff --name-only HEAD ${{ github.event.pull_request.base.sha }} | 
                    grep -E 'members/[^/]+/task[^/]+/' | 
                    cut -d'/' -f1-3 | 
                    sort | uniq)
          echo "changed_tasks=${CHANGED}" >> $GITHUB_OUTPUT
      - name: Build changed tasks
        if: steps.changed.outputs.changed_tasks != ''
        run: |
          for task in ${{ steps.changed.outputs.changed_tasks }}; do
            echo "Building $task"
            cd "$task" && mkdir -p build && cd build
            cmake .. && make
            if [ -f "solution" ]; then
              echo "Running solution:"
              ./solution
            fi
            cd ../../..
          done
