name: Push Check

on:
  push:
    branches: [main, master]

jobs:
  validate_push:
    runs-on: ubuntu-latest
    container:
      image: gcc:latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install -y clang-format

      - name: Build and test all tasks
        run: |
          if [ -z "$(ls -A members/*/* 2>/dev/null)" ]; then
            echo "No tasks found in members directory"
            exit 1
          fi
          
          make all
          
          make format
          git diff --exit-code
